Student-Center/weave-server

.github/workflows/sonar_cloud.yaml
bootstrap/http/build.gradle.kts
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
build.gradle.kts
buildSrc/src/main/kotlin/Version.kt

Sonar Cloud 관련 설정이에요
main 브렌치에 대해 pr시 동작해요

[WEAV-16] 🔧 SonarCloud 관련 설정

---

README.md

[WEAV-32] fix githook path

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshLoginTokenResponse.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/SocialLoginResponse.kt

[WEAV-46] Open API3 영어로 변경

---

bootstrap/http/compose-dev.yaml

docker compose pull policy 변경해서 캐시 해제했습니다

[WEAV-50] 개발서버내 docker cache로 인한 CD 반영 안됨 이슈 해결

---

.github/workflows/cd_dev.yaml

개발서버내 local docker 이미지로 인한 배포 이슈 해결 PR이에요.
이전 PR로 해결 안된부분이 있어서 다시 올려요

[WEAV-50] 개발 서버 배포 이슈 해결

---

domain/src/test/kotlin/com/studentcenter/weave/domain/entity/DeactivateUserInfoTest.kt
domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserTest.kt
domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/UserFixtureFactory.kt

이전에 User 객체 파라미터 수정한 내용이 테스트 코드에는 반영되어있지 않아서 수정했어요.
pr단계에서 codecoverage측정 안되는 이슈를 해결했어요

[WEAV-51] 테스트 코드 수정

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshTokenRequest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/SocialLoginRequest.kt

[WEAV-63] 로그인 API 파라미터명 수정

---

application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategy.kt
application/src/test/kotlin/com/studentcenter/weave/application/service/domain/impl/UserAuthInfoDomainServiceImplTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImplTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/KakaoOpenIdTokenResolveStrategyTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/JwtTokenPropertiesFixtureFactory.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/OpenIdPropertiesFixtureFactory.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserAuthInfoRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/util/impl/strategy/OpenIdTokenResolveStrategyStub.kt

- #23 이전 PR에서 누락된 테스트 구현했어요
- UserTokenService에서 일부 잘못된 구현 수정했어요(UUID string으로 변환안하고 jwt 인코딩)

[WEAV-108] 토큰서비스 테스트 구현

---

infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/MajorJpaEntity.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UniversityJpaEntity.kt
infrastructure/persistence/src/main/resources/db/migration/V2__Create_universities_and_majors.sql

- univ, major 관련 table 및 jpa entity 정의

[WEAV-107] Add university and major flyway and jpa entity

---

infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/MajorJpaEntity.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UniversityJpaEntity.kt
infrastructure/persistence/src/main/resources/db/migration/V2__Create_universities_and_majors.sql

- JPA Entity 수정 및 Flyway tailling comma 제거
- flyway 잘 동작

[WEAV-107] fix jpa entity & remove sql trailing comma

---

application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserRegisterUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationService.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UserApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserResponse.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/WebMvcConfig.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/annotation/RegisterTokenClaim.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/resolver/RegisterTokenArgumentResolver.kt

작업내용
- 회원가입 토큰 리졸버 Argumentresovler 개발
- RegisterUserUseCase 개발
- 회원가입 API Swagger 명세 수정

[WEAV-77] 회원가입 토큰 리졸버 및 RegisterUserUseCase 인터페이스 개발

---

application/build.gradle.kts
application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserAuthInfoRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserAuthInfoDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/domain/impl/UserAuthInfoDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/domain/impl/UserDomainServiceImpl.kt
application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationServiceTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/service/domain/impl/UserDomainServiceImplTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserAuthInfoRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/domain/UserDomainServiceStub.kt
buildSrc/src/main/kotlin/Version.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserAuthInfoJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserJpaAdapter.kt

[WEAV-119] 회원가입 유스케이스 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/common/exception/AuthExceptionType.kt
application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserRefreshTokenUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserRefreshTokenApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRefreshTokenApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepositorySpy.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshLoginTokenResponse.kt
infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/adapter/UserRefreshTokenRedisAdapter.kt

- 토큰 갱신 API구현했어요.
- id값으로 표현했던 내용들 userId로 조금더 명시적으로 변경했어요

[WEAV-125] 토큰 갱신 API 구현

---

bootstrap/http/src/main/resources/application.yaml
infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/common/config/RedisConfig.kt
infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/common/properties/RedisProperties.kt
infrastructure/redis/src/main/resources/application-redis.yaml

- bootstrap 에 applicaiton yaml파일에, applicaiton-redis.yaml 설정 포함 누락
🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲

[WEAV-76] Reids Connection Refused 문제 해결

---

application/src/main/kotlin/com/studentcenter/weave/application/common/exception/AuthExceptionType.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserLogoutApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserLogoutApplicationServiceTest.kt

USER_NOT_AUTEHNTICATED? 애플리케이션 레이어에서 security context가 비었을때 에러 이름을 뭘로할지 고민이네요,

[WEAV-158] 로그아웃 유스케이스 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserUnregisterUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserUnregisterApplicationService.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt

DELETE /api/user
response - 204 nocontent

[WEAV-156] 회원 탈퇴 API - Bootstrap 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetMyProfileUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationServiceTest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt

- 회원 정보 조회 유스케이스 구현이에요
- 이메일 인정 여부 확인 및 전공 도메인 서비스가 아직 미구현 상태라 TODO 주석으로 남겨두었어요

[WEAV-129] 유저 정보 조회 유스케이스 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyHeightUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationServiceTest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserSetMyHeightRequest.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/UpdateParam.kt

[WEAV-169] 회원 키설정 API 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamCreateUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamCreateRequest.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/enums/MeetingTeamStatus.kt
domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingTeamJpaRepository.kt
infrastructure/persistence/src/main/resources/db/migration/V7__meeting_team_add_status_column.sql

[WEAV-175] 미팅 팀 생성 API 구현

---

domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserSil.kt
domain/src/test/kotlin/com/studentcenter/weave/domain/user/entity/UserSilTest.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/UserSilJpaEntity.kt
infrastructure/persistence/src/main/resources/db/migration/V8__create_user_sil.sql

유저 실은 기본 프로필에 컬럼으로 두지않고 별도 테이블로 분리했어요.

[WEAV-177] 유저 실 도메인 정의

---

application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetMyProfileUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetMyProfileResponse.kt

- 대학 이름 누락된 부분 추가했어요
- 대학, 전공 도메인 서비스 나오면 조회 연결할 예정이에요

[WEAV-129] 유저 본인 정보 조회 API 응답, 대학 이름 누락 추가

---

application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationServiceTest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
infrastructure/persistence/src/main/resources/db/migration/V11__change_meeting_team_add_gender.sql

- 미팅 팀에 Gender Column 추가했어요
- 미팅팀 API swagger명세 description으로 되어있는부분 summary로 수정했어요

[WEAV-176] 미팅팀 Gender 컬럼 추가

---

application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamGetMyUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyRequest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollRequest.kt
support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt

Scroll Request, Scroll Response 에 id필드 제거하고 제네릭 활용해서 next로 변경했어요

[WEAV-187] 내 미팅팀 조회 모의응답 API 요청 & 응답 수정

---

infrastructure/mail/src/main/kotlin/com/studentcenter/weave/infrastructure/mail/adaptor/VerificationNumberGmailAdaptor.kt

[WEAV-191] 메일 디버그용 에러 로그 추가

---

.github/workflows/develop_server_deployer.yaml
.github/workflows/develop_server_integrator.yaml

- CI 불필요한 환경 값 제거
- CD에 EMAIL 관련 환경 변수 추가

[WEAV-191] Fix Ci/Cd env file injection

---

application/src/main/kotlin/com/studentcenter/weave/application/university/port/outbound/MajorRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/university/service/domain/MajorDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/university/service/domain/impl/MajorDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/university/port/outbound/MajorRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/university/port/outbound/UniversityRepositorySpy.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/adapter/MajorJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/adapter/UniversityJpaAdapter.kt

- 나의 프로필 응답에 학교, 학과 이름과 인증 여부 로직 추가 및 테스트 수정
- 하위호환성을 위한 기존 유저의 학교 학과 데이터 수정

[WEAV-193] 프로필 응답 구현 및 테스트 추가

---

.github/workflows/develop_server_deployer.yaml

- CD 작업에서 compose up 전에 동일한 폴더에 .env 파일을 생성하는 작업 추가

[WEAV-192] CD github action .env 생성 작업 추가

---

domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/enums/Location.kt

[WEAV-197] 위치 데이터에 시흥시 추가

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetDetailResponse.kt

<h2>Background</h2>
<p><img src="https://github.com/Student-Center/weave-server/assets/28651727/df663684-77a2-496f-a974-bb815c79370a" width=200px alt="Untitled"></p>
<h2>Goals &amp; Non-Goals</h2>
<h3>Goals</h3>
<ul>
<li>
<p>미팅팀 상세정보 응답</p>
<ul>
<li>미팅팀 소속된 멤버 상세 정보 응답</li>
</ul>
</li>
<li>
<p>필요한 정보</p>
</li>
<li>
<p>미팅팀</p>
<ul>
<li>미팅팀 소개</li>
<li>미팅팀 지역</li>
<li>미팅팀 성별</li>
<li>미팅팀 멤버 정보
<ul>
<li>MBTI, 얼굴상, 키, 대학교, 학과, 년생</li>
</ul>
</li>
<li>미팅팀과의 케미 (보류)</li>
</ul>
</li>
</ul>
<hr>
<h2><strong>Methodology &amp; Design(Proposal)</strong></h2>
<h3>API</h3>
<p><strong>GET api/meeting-teams</strong></p>
<ul>
<li><strong>Auth Required:</strong> Yes (토큰 기반 인증을 사용, 요청 헤더에 <strong><code>Authorization: Bearer &lt;token&gt;</code></strong> 포함)</li>
<li><strong>Request</strong>
<ul>
<li> …

[WEAV-217] 미팅팀 목록 상세 기능 API 모의 응답 구현

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/api/UnivApi.kt

[WEAV-244] API 경로 수정

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamGetDetailUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingMemberDetailInfo.kt
application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/MajorGetByIdUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/university/port/inbound/UniversityGetByIdUsecase.kt
application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/MajorGetByIdApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetByIdUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetByIdApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/university/service/application/UniversityGetByIdApplicationServiceTest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetDetailResponse.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/university/controller/UnivRestController.kt

<h2>Background</h2>
<p><img src="https://github.com/Student-Center/weave-server/assets/28651727/b7514a74-7714-465f-844e-1d2a2ad8a55b" alt="Untitled" width=200px></p>
<h2>Goals &amp; Non-Goals</h2>
<h3>Goals</h3>
<ul>
<li>
<p>미팅팀 상세정보 응답</p>
<ul>
<li>미팅팀 소속된 멤버 상세 정보 응답</li>
</ul>
</li>
<li>
<p>필요한 정보</p>
</li>
<li>
<p>미팅팀</p>
<ul>
<li>미팅팀 소개</li>
<li>미팅팀 지역</li>
<li>미팅팀 성별</li>
<li>미팅팀 멤버 정보
<ul>
<li>MBTI, 얼굴상, 키, 대학교, 학과, 년생</li>
</ul>
</li>
</ul>
</li>
</ul>
<h3>Non-Goals</h3>
<ul>
<li>미팅팀과의 케미 (보류)</li>
</ul>
<h2><strong>Methodology &amp; Design(Proposal)</strong></h2>
<h3>API</h3>
<p><strong>GET api/meeting-teams</strong></p>
<ul>
<li><strong>Auth Required:</strong> Yes (토큰 기반 인증을 사용, 요청 헤더에 <strong><code>Authorization: Bearer &lt;token&gt;</code></strong> 포함)</li> …

[WEAV-218] 미팅 팀 상세조회 유스케이스 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/common/exception/UniversityVerificationExceptionType.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserUniversityVerificationInfoRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserSendVerificationNumberEmailApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserVerifyVerificationNumberApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/UserUniversityVerificationInfoDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserUniversityVerificationInfoDomainServiceImpl.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSendVerificationNumberEmailApplicationServiceTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserVerifyVerificationNumberApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserUniversityVerificationInfoRepositorySpy.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserUniversityVerificationInfoFixtureFactory.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserUniversityVerificationInfoJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserUniversityVerificationInfoJpaRepository.kt

-  대학 인증 과정에서 이미 인증된 메일과 유저에 대한 방어로직 추가

[WEAV-226] 인증된 이메일 및 유저에 대한 방어로직 추가

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamGetListUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamGetMyUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetListApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MyMeetingTeamInfo.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetListRequest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetListResponse.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetMyResponse.kt
support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt

- 미팅팀 목록조회 모의 API 응답 구현
- UseCase 구현, DomainService 미구현
- MeetingTeamInfo, MyMeetingTeamInfo VO클래스 분리
##
<h2>Background</h2>
<h2>Goals &amp; Non-Goals</h2>
<h3>Goals</h3>
<ul>
<li>홈화면 미팅팀 목록 조회
<ul>
<li>내가 찾는 미팅 (2:2, 3:3, 4:4) 필터</li>
<li>미팅 상대팀 나이 필터</li>
<li>선호 미팅 지역 필터 (개수 제한 없음 - 미선택시 전체)</li>
</ul>
</li>
</ul>
<h3>Non goals</h3>
<ul>
<li>정렬 순서 (우선 최신 등록순으로 정렬 id -desc)
<ul>
<li>추후 추천 알고리즘 구현</li>
</ul>
</li>
</ul>
<hr>
<h2><strong>Methodology &amp; Design(Proposal)</strong></h2>
<h3>API</h3>
<p><strong>GET api/meeting-teams</strong></p>
<ul>
<li><strong>Auth Required:</strong> Yes (토큰 기반 인증을 사용, 요청 헤더에 <strong><code>Authorization: Bearer &lt;token&gt;</code></strong> 포함)</li>
<li><strong>Request</strong>
<ul>
<li>
<p>method &amp; path: <code>[GET] /meeting-teams</code></p>
</li> …

[WEAV-153] 미팅팀 목록조회 모의 API 응답 구현 및 UseCase 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamGetListUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetListApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingTeamListFilter.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetListRequest.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/enums/Gender.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt

- 홈화면 미팅팀 목록 조회
- 내가 찾는 미팅 (2:2, 3:3, 4:4) 필터
- 미팅 상대팀 나이 필터
- 선호 미팅 지역 필터 (개수 제한 없음 - 미선택시 전체)
- 사용자의 성별에 따라 반대 성별 팀의
- 정렬 순서 (우선 최신 등록순으로 정렬 id -desc)
- 추후 추천 알고리즘 구현
---
**GET api/meeting-teams**
- **Auth Required:** Yes (토큰 기반 인증을 사용, 요청 헤더에 **`Authorization: Bearer <token>`** 포함)
- **Request**
- method & path: `[GET] /meeting-teams`
- query params
| Parameter | Type | Description | Required |
| --- | --- | --- | --- |
| memberCount | integer | 찾는 미팅 팀의 멤버수 | No |
| youngestMemberBirthYear | integer | 미팅 상대팀 멤버의 최소 년생 (06 ~ 97) | Yes |
| oldestMemberBirthYear | integer | 미팅 상대팀 멤버의 최대 년생 (97 ~ 05) youngestMemberBirthYear ≥ oldestMemberBirthYear | Yes |
| preferredLocations | List<Location> | 선호하는 미팅 지역. 여러 지역 선택 가능, 쉼표(,)로 구분. 미선택시 전체 지역을 대상으로 조회 | No |
| next | UUID | 이전 요청의 마지막 item …

[WEAV-153] 미팅팀 목록조회 API

---

infrastructure/mail/src/main/resources/mail-templates/email-verification-number.html

- 이메일 템플릿 변경
| 변경 전                 | 변경 후                      |
|--------------------------|-------------------------------|
| <img width="400" alt="image" src="https://github.com/Student-Center/weave-server/assets/61923768/836eed4b-3a5d-430a-8313-19797b9ff1bd"> | <img width="400" alt="image" src="https://github.com/Student-Center/weave-server/assets/61923768/1125dd6b-09f7-4ff1-80be-1c7fc970b371"> |

[WEAV-000] Email Template 변경

---

application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationServiceTest.kt

- mock이 제대로 clear되지 않아서 테스트가 실패 -> mock 제거 로직 추가

[WEAV-000] 테스트 실패 버그 해결

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationServiceTest.kt

- 미팅팀 공개상태일 경우 수정이 불가능 하도록 validation 추가했어요

[WEAV-203] 팀 공개시 수정 불가

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/OpenApiConfig.kt
bootstrap/http/src/main/resources/application.yaml

[WEAV-000] Open API Url 변경

---

application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingExceptionType.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingAttendanceCreateUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingAttendanceRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingAttendanceDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingAttendanceDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamMemberQueryUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingMemberRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamMemberQueryApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamMemberDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamMemeberDomainServiceImpl.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingAttendanceRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingAttendanceCreateRequest.kt
bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/MeetingAttendanceCreateApplicationServiceIntegrationTest.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/Meeting.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingAttendanceJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingAttendanceJpaRepository.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingMemberJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingMemberJpaRepository.kt

[WEAV-259] 미팅 참여 / 패스 로직 처리

---

application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/FindMyRequestMeetingByReceivingTeamIdUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/FindMyRequestMeetingByReceivingTeamIdApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/FindByRequestingTeamIdAndReceivingTeamIdApplicationServiceTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/FindMyRequestMeetingByReceivingTeamIdApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingResponse.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt

[WEAV-265] 해당 team에 대한 요청 조회

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetDetailResponse.kt

[WEAV-000] 유저 이메일 확인 여부 응답 추가

---

application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/FindMyRequestMeetingByReceivingTeamIdApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/ScrollPendingMeetingApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/FindMyRequestMeetingByReceivingTeamIdApplicationServiceTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/ScrollPendingMeetingApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt

[WEAV-000] Apply custom exception

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/MeetingTeamDomainServiceIntegrationTest.kt

- 멤버 수 줄일 때 현재 인원 수 크기와 같아도 수정 가능
- 수정 후 멤버 수가 현재 인원 수와 같다면 팀 공개 추가

[WEAV-000] Fix member updatable

---

domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummary.kt

[WEAV-000] Fix summary member birth

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt

[WEAV-000] Fix my team member order

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamInfoGetAllByIdApplicationService.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/adapter/MajorJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/university/adapter/UniversityJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserJpaRepository.kt

[WEAV-000] Fix user major id

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PendingMeetingScrollResponse.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollResponse.kt

- 스크롤 조회의 학교 이름을 display_name으로 변경

[WEAV-000] 스크롤 조회 university 수정

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationServiceTest.kt

- 미팅 상세 조회 내 팀 조회 get -> find
- 테스트 작성

[WEAV-000] 미팅 팀 상세 조회 내가 속한 팀이 없어도 조회되도록 변경

---

.github/workflows/unit_test_runner.yaml
application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserGetProfileImageUploadUrlUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPort.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserGetProfileImageUploadUrlApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/vo/ImageFileExtension.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetProfileImageUploadUrlApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPortStub.kt
bootstrap/http/build.gradle.kts
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserGetProfileImageUploadUrlResponse.kt
bootstrap/http/src/main/resources/application.yaml
buildSrc/src/main/kotlin/Version.kt
infrastructure/aws/build.gradle.kts
infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/config/AwsConfig.kt
infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/adapter/UserProfileImageUrlS3Adapter.kt
infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/config/S3BucketProperties.kt
infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/config/S3Config.kt
infrastructure/aws/src/main/resources/application-aws.yaml
settings.gradle.kts

- [설계 문서](https://www.notion.so/weave-org/9e998df857af46ceaf27af4755427bc7?p=4eec733604544f9d9800407b4a2a1ed3&pm=s)

[WEAV-266] 회원 프로필 이미지 업로드 Presigned URL 조회 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/common/exception/UserExceptionType.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserCompleteProfileImageUploadUseCase.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPort.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserCompleteProfileImageUploadApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserCompleteProfileImageUploadApplicationServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserProfileImageUrlPortStub.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/api/UserApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/controller/UserRestController.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
infrastructure/aws/src/main/kotlin/com/studentcenter/weave/infrastructure/aws/s3/adapter/UserProfileImageUrlS3Adapter.kt
infrastructure/aws/src/main/resources/application-aws.yaml

- [설계 문서 ](https://www.notion.so/weave-org/9e998df857af46ceaf27af4755427bc7?p=4eec733604544f9d9800407b4a2a1ed3&pm=s)

[WEAV-266] 유저 프로필 이미지 업로드 콜백 구현

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollResponse.kt

[WEAV-000] Prepared member response avatar 추가

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetListApplicationService.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt

- Scroll 로직 변경(next는 limit 사이즈보다 더 크게 조회해서 다음 것이 있는지 체크)
- Limit 쿼리 수정(id는 증가하므로 id desc로 정렬한 뒤 next id보다 작거나 같은 id로 조회)

[WEAV-000] Fix scroll meeting team

---

infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt

- order by 추가 및 next id 동등 조건 추가

[WEAV-000] Fix order by 추가 next 동등 조건 추가

---

.github/workflows/develop_server_deployer.yaml
.github/workflows/develop_server_integrator.yaml
bootstrap/http/compose-dev.yaml

- Dev CD 실행시 버저닝 파라미터 삽입 가능(latest or 0.2411.135 형식)
- 기존 CI 수행시 태깅 -> CD 수행시에만 해당 버전으로 태그 달리도록 수정
> gitaction특성상 로컬 테스트가 안되서 수정 PR계속 날라갈수 있어용

[WEAV-294] 👷 CD시 배포로 수정

---

.github/workflows/develop_server_deployer.yaml

- 동일 커밋에 동일 태그가 중복으로 작성될시 422응답이 오면, 스킵하도록 수정

[WEAV-000] 태그 중복 작성 방지 로직

---

.github/workflows/develop_server_deployer.yaml
.github/workflows/develop_server_integrator.yaml
bootstrap/http/compose-dev.yaml

- 버전 pull시 명시적인 버전을 전달하지 않을 경우 태그없이 pulling해 최신버전을 가져오도록 변경
- 환경변수 일일이 등록 -> .env파일 전달로 변경

[WEAV-000] 버전 pull 관련 이슈 해결

---

.github/workflows/develop_server_deployer.yaml
bootstrap/http/compose-dev.yaml

[WEAV-000] compose 파일 버전 오타 수정

---

.github/workflows/develop_server_deployer.yaml
application/src/main/resources/application-application.yaml
bootstrap/http/compose-dev.yaml
bootstrap/http/src/main/resources/application.yaml
infrastructure/persistence/src/main/resources/application-persistence.yaml
infrastructure/redis/src/main/resources/application-redis.yaml

- 이전에 github secret에서 dev, prod가 prefix를 통해 관리되고 있던부분을 github environment를 통해 관리하는것으로 변경하기 위한 PR입니다.
- gitaction 상에서 다음과 같이 environment 값을 통해 어떤 환경 변수 세트를 사용할지 결정할 수 있습니다.
- 환경변수는 repository setting -> environment 에서 확인하실 수 있습니다. [link](https://github.com/Student-Center/weave-server/settings/environments/2484412974/edit)
```
jobs:
deploy:
needs: validate_version
runs-on: ubuntu-latest
environment: DEV
```

[WEAV-295] 서버 환경변수 정리

---

.github/workflows/production_server_deployer.yaml

- 배포 서버 워크플로우 작성
- 기존 discord 메세지 마크다운 형식 적용

[WEAV-296] 배포 서버 CD 워크플로우 작성

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/filter/ExceptionHandlingFilter.kt

[WEAV-000] 예외 핸들링 필터 순서 수정

---

application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationServiceTest.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt

[WEAV-000] 유저 정보 update시 UpdateAt 반영

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamDeleteApplicationService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationService.kt
application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamDeleteApplicationServiceTest.kt

- 미팅 팀 나가기/삭제 시에 요청에 대한 처리 및 권한 체크 추가

[WEAV-000] Fix leave/delete meeting team side effect

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/scheduler/component/PendingMeetingExpireScheduler.kt

[WEAV-000] Change cron schedule

---

bootstrap/http/compose-dev.yaml
bootstrap/http/compose-local.yaml

- mysql 영속성을 위해 볼륨 추가
- mysql tz 환경 변수 추가

[WEAV-000] Add mysql volume

---

application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetMyApplicationService.kt

[WEAV-000] Fix my team scroll next 처리

---

.github/workflows/pr_validator.yml
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollResponse.kt

[WEAV-00] Fix prepared team location name -> value

---

bootstrap/http/src/main/resources/static/.well-known/apple-app-site-association

[WEAV-000] 앱링크 asset 추가

---

application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingTeamExceptionType.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/GetMeetingTeam.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/GetMeetingTeamDetail.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/GetMeetingTeamDetailService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/GetMeetingTeamService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingMemberDetail.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamGetDetailResponse.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamMemberDetailResponse.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingMemberJpaRepository.kt

<h3>GET /api/meeting-teams/{teamId}/members/{memberId}</h3>
<p><strong>Request</strong></p>
<ul>
<li>Path Variable
<ul>
<li>teamId : 미팅팀 아이디</li>
<li>memberId : 멤버 아이디</li>
</ul>
</li>
</ul>
<p><strong>Response</strong></p>
```json
{
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"user": {
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"mbti": "string",
"animalType": "string",
"height": 0,
"profileImages": [
"http://s3.~~.img"
],
"birthYear": 0,
"isUnivVerified": true
}
}
```
| 필드명 | 타입 | 설명 |
| --- | --- | --- |
| id | String (UUID) | 응답의 고유 식별자 |
| [user.id](http://user.id/) | String (UUID) | 유저의 고유 식별자 |
| user.mbti | String | 유저의 MBTI |
| user.animalType | String (Optional) | 유저의 동물상 |
| user.height | Integer (Optional) | 유저의 키 (단위: cm) |
| user.birthYear | Integer | 유저의 출생 년도 |
| …

[WEAV-318] 미팅 멤버 프로필 상세 보기 API

---

application/src/main/kotlin/com/studentcenter/weave/application/chat/port/inbound/GetChatRoom.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/port/outbound/ChatRoomRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/service/GetChatRoomService.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/vo/ChatRoomDetail.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/GetUser.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/GetUserService.kt
application/src/test/kotlin/com/studentcenter/weave/application/chat/service/GetChatRoomServiceTest.kt
application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/CreateMeetingTeamTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/chat/outbound/ChatRoomRepositorySpy.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/inbound/GetUserStub.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepositorySpy.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeam.kt
domain/src/test/kotlin/com/studentcenter/weave/domain/chat/entity/ChatRoomTest.kt
domain/src/test/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessageTest.kt
domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamFixtureFactory.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/adapter/ChatRoomJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/UserJpaRepository.kt

```mermaid
classDiagram
class GetChatRoom {
+getDetailById(id: UUID): ChatRoomDetail
}
class GetChatRoomService {
-getUser: GetUser
-getMeetingTeam: GetMeetingTeam
-chatRoomRepository: ChatRoomRepository
+getDetailById(id: UUID): ChatRoomDetail
}
class ChatRoomDetail {
+id: UUID
+myTeam: Team
+otherTeam: Team
}
class Team {
+id: UUID
+name: String
+members: List<Member>
}
class Member {
+id: UUID
+name: String
+avatar: Url?
}
class ChatRoomRepository {
+getById(id: UUID): ChatRoom
}
class GetUser {
+getById(id: UUID): User
}
class GetMeetingTeam {
+getById(id: UUID): MeetingTeam
}
GetChatRoomService ..|> GetChatRoom
GetChatRoomService --> GetUser
GetChatRoomService --> GetMeetingTeam
GetChatRoomService --> ChatRoomRepository
GetChatRoomService ..> ChatRoomDetail
ChatRoomDetail *-- Team …
```

[WEAV-322] 채팅방 상세정보 조회 유스케이스 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/SendVerificationEmailService.kt
infrastructure/persistence/src/main/resources/db/seed/230408_insert_temp_university_major.sql
infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/user/entity/UserVerificationNumberRedisHash.kt

- Redis Hash 변경
- 이미 유효한 번호가 있고 이메일이 같다면 별도로 번호를 생성하지 않고 재사용하도록 변경
- 테스트를 위한 임시 대학 및 학과 추가

[WEAV-000]refactor send verification number logic

---

application/src/main/kotlin/com/studentcenter/weave/application/chat/port/inbound/SendChatMessage.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/service/SendChatMessageService.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/vo/UserAuthentication.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/chat/controller/ChatWebSocketController.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/WebSocketConfig.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/StompAuthInterceptor.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/StompExceptionHandler.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/WebSocketAuthInterceptor.kt
support/security/src/main/kotlin/com/studentcenter/weave/support/security/authority/Authentication.kt

```mermaid
sequenceDiagram
participant User
participant WebSocketConfig
participant WebSocketAuthInterceptor
participant ChatWebSocketController
participant SendChatMessageService
User ->> WebSocketConfig: CONNECT
WebSocketConfig ->> WebSocketAuthInterceptor: 인증 처리 요청
alt 인증 실패
WebSocketAuthInterceptor -->> WebSocketConfig: 인증 실패 예외 발생
WebSocketConfig -->> User: ERROR (인증 실패)
else 인증 성공
WebSocketAuthInterceptor -->> WebSocketConfig: 인증 결과 반환
WebSocketConfig -->> User: CONNECTED
User ->> ChatWebSocketController: SUBSCRIBE
ChatWebSocketController -->> User: 구독 확인
User ->> ChatWebSocketController: SEND
ChatWebSocketController ->> SendChatMessageService: 채팅 메시지 전송 요청
SendChatMessageService -->> ChatWebSocketController: 채팅 메시지 전송 결과
ChatWebSocketController -->> User: MESSAGE
end
```
```json
[ …
```

[WEAV-327] 채팅 유저 인증 개발

---

application/src/main/kotlin/com/studentcenter/weave/application/chat/port/outbound/ChatMessageRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/service/SaveChatMessageService.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/ChatMessage.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/adapter/ChatMessageJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/enitty/ChatMessageJpaEntity.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/repository/ChatMessageJpaRepository.kt
infrastructure/persistence/src/main/resources/db/migration/V20__create_chat_message.sql

- 채팅 메시지 저장 SaveChatMessage 유스케이스 구현

[WEAV-326] 채팅 메시지 저장 기능 구현

---

application/src/main/kotlin/com/studentcenter/weave/application/chat/port/inbound/CreateChatRoom.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/port/outbound/ChatRoomRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/chat/service/CreateChatRoomService.kt
application/src/test/kotlin/com/studentcenter/weave/application/chat/service/CreateChatRoomServiceTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/chat/outbound/ChatRoomRepositorySpy.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/adapter/ChatRoomJpaAdapter.kt
infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/enitty/ChatRoomJpaEntity.kt

- 채팅방 생성을 위한 유스케이스를 구현했어요
- 매칭이벤트를 수신해 생성을 호출하는 부분은 다음 PR에 구현할 예정이에요

[WEAV-330] 채팅방 생성 유스케이스 구현

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/ChatMessage.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/ChatRoom.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingAttendance.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingMember.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeam.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummary.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/university/entity/Major.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/university/entity/University.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/DeletedUserInfo.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserAuthInfo.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserProfileImage.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserSil.kt
domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/UserUniversityVerificationInfo.kt
infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/chat/config/ChatMessageRedisConfig.kt

- 이전에 MeetingDomain에 적용했던 AggregateRoot, Domain Entity를 전체 도메인에 적용했어요

[WEAV-000] AggregateRoot, Domain Entity 인터페이스 상속 적용

---

bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt

- NoResourceFoundException 로그에 쿼리 스트링이 있다면 함께 로깅합니다

[WEAV-000] Add query string NoResourceFoundException error message

---

infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/meeting/adaptor/MeetingEventMessageDiscordAdaptor.kt
infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt

- 디스코드 메세지에 prefix로 `@everyone`을 추가하여 멘션

[WEAV-000] Add discord event message method prefix 

---

infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/meeting/adaptor/MeetingEventMessageDiscordAdaptor.kt
infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt

[WEAV-000] Fix log message

---

application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRefreshTokenRepository.kt
application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/RefreshTokenService.kt
application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/LogoutTest.kt
application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRefreshTokenRepositorySpy.kt
infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/user/adapter/UserRefreshTokenRedisAdapter.kt

- 리프레쉬 토큰 만료 예외 변경
- 리프레쉬 토큰 조회 메서드 변경

[WEAV-000] 리프레쉬 토큰 만료 예외 변경 및 토큰 조회 메서드 리팩토링

---

.github/workflows/develop_server_deployer.yaml

[WEAV-000] dev server cd trigger by ci

---

bootstrap/http/build.gradle.kts
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt
bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/WebSocketExceptionHandler.kt
bootstrap/http/src/main/resources/application.yaml
gradle/libs.versions.toml

- 에러로그 모니터링을 위한 센트리 연동
- 버전은 latest(`7.8.0`)로 적용해두었어요. - [Sentry Docs](https://docs.sentry.io/platforms/java/guides/spring-boot/)
- CustomException은 400번대 에러인 것 같아 적용해두지 않았는데 의견 주시면 반영해볼게요.
- 센트리 가입을 해야하는데 공용으로 관리하는 구글계정이 있다면 해당 계정으로 로그인해서 같이 관리하는 방향을 생각하고 있어요.
- (혹시라도 사용중인 계정이 있다면 공유부탁드립니다.)
- 회원가입 후에 프로젝트 생성되면 dsn 적용해놓을게요.

[WEAV-315] Sentry 라이브러리 연동

---

.github/workflows/develop_server_deployer.yaml

[WEAV-000] Fix cd image version
