Student-Center/weave-server

- .github/workflows/pr-title-validation.yml
PR title validation 을 위한 gitaction입니다.
[WEAV-번호] 형식인지만 체크해요~
> [WEAV-30] Add PR title validation workflow

- buildSrc/src/main/kotlin/Version.kt
- support/common/build.gradle.kts
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/uuid/UuidCreator.kt
> [WEAV-31] ✨ UUID Creator Util 설정

- bootstrap/http/build.gradle.kts
- bootstrap/http/compose-dev.yaml
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RefreshLoginTokenResponse.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/SocialLoginResponse.kt
- bootstrap/http/src/main/resources/application.yaml
- buildSrc/src/main/kotlin/Version.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/enum/SocialLoginProvider.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/Email.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/Url.kt
- support/common/src/test/kotlin/com/studentcenter/weave/support/common/vo/EmailTest.kt
- support/common/src/test/kotlin/com/studentcenter/weave/support/common/vo/UrlTest.kt
- 소셜 로그인 API with 모의응답
- 소셜 로그인시 회원가입 되어있을 경우 -> 로그인 토큰 응답(access token, refresh token) 
- 소셜 로그인시 회원가입이 되어있지 않을 경우 -> 클라이언트에게 회원가입에 필요한 정보 토큰으로 제공(이메일, 닉네임, 소셜로그인 제공자)
- 로그인 토큰 갱신 API with 모의 응답
> [WEAV-20] ✨ 소셜 로그인 API 모의 응답 구현

- .github/workflows/ci_dev.yaml
- Dockerfile-http
- bootstrap/http/compose-dev.yaml
- bootstrap/http/compose-local.yaml
- bootstrap/http/src/main/resources/application.yaml
- buildSrc/src/main/kotlin/Version.kt
- infrastructure/persistence/build.gradle.kts
- infrastructure/persistence/src/main/resources/application-persistence.yaml
CI 작업하다보니 계속 길어져서 일단 여기서 끊고 완료되면 CD랑 인프라 작업 진행하려구요
- 영속성 관련 설정(지금 안해두면 나중에 CI 설정 에 또 반영해야해서 미리 설정해두었어요)
- local, dev는 설정 노출되어있긴 한데, 프로덕션이 아니라 크게 문제없을것 같아요
1. main브렌치에 push
2. aws의 public container registry에 도커이미지 빌드, push
3. compose-dev.yaml : 깃레포에서 인스턴스로 복사
4. 인스턴스에서 `docker compose up -d` 명령어 수행
```yaml
services:
spring:
image: public.ecr.aws/h3l4i6v1/weave_server_dev_cr
...
```
docker container registry의 경우에는 dev, prod 레지스트리 나눌려고 해요
- main push -> image build -> dev registry -> 개발 ec2 instance (docker compose up)
- release push -> image build -> prod registry -> 배포 ec2 instance (elastic beanstalk or ec2 + AWS RDS + ...)
> [WEAV-21] ✨ 개발서버 CI workflow 구현

- application/build.gradle.kts
- application/src/main/kotlin/com/studentcenter/weave/application/common/config/ApplicationConfig.kt
- application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserSocialLoginUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/service/UserTokenService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserAuthInfoDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/service/domain/UserDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/vo/UserTokenClaims.kt
- application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/UserTokenServiceStub.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/service/domain/UserDomainServiceStub.kt
Service의 의존관계가 복잡해질것을 감안해 Service레이어를 ApplicationService, DomainService로 나누었어요. 
n-layered 아키텍처에서 사용하는 Facade처럼 Application Service를 활용한다고 생각하시면 될것같아요
DomainService의 경우 해당 도메인에만 관련있는 로직(CRUD 등)을 수행하고, ApplicationService의 경우 여러 도메인의 Service를 활용해 UseCase를 구현한다고 보시면 되요
Cotroller -> ApplicationService(UseCase) -> DomainService -> Repository, Handler
ApplicationService의 경우 InboundPort인 UseCase를 구현하고,
DomainService의 경우 별도로 인터페이스가 없기때문에 DomainServiceImpl로 구현객체 따로 만들려고 생각하고있어요.
테스트 단계에서 목사용을 최소화 하고 Fake객체를 사용하기 위함이고 Fake객체를 만들기 위해서는 Fake객체를 만드려는 대상 객체의 인터페이스가 존재해야하기때문이에요.
> [WEAV-49] 로그인 기능 애플리케이션 레이어 구현

- application/src/main/kotlin/com/studentcenter/weave/application/common/properties/JwtTokenProperties.kt
- buildSrc/src/main/kotlin/Version.kt
- settings.gradle.kts
- support/security/build.gradle.kts
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtExpiredException.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtVerificationException.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProvider.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/vo/JwtClaims.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/vo/JwtClaimsDsl.kt
- support/security/src/test/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProviderTest.kt
토큰 resolve를 위한 auth0라이브러리의 래핑을 위해 아래 내용은 support/security 라는 모듈을 따로 만들어 개발해두었습니다. 
JwtTokenProvider는 외부 의존성 주입받아 사용하지 않고, Spring생명주기가 필요없기때문에 공통모듈에 유틸리티 클래스로 만들어두었어요.
JwtClaims는 코틀린 DSL활용해서 생성할 수 있게끔 정의해 두었어요.
JwtTokenProvider의 Jwks Uri를 통해 resolve하는 로직은 어떻게 테스트 할지 고민중이에요.(verifyJwksBasedToken 함수)
해당 함수의 경우 카카오측에서 private key로 서명한 idToken을 카카오의 jwks uri로 전달받을수 있는 public key로 토큰에 대한 검증을 할 수 있는데, 
```kotlin
fun verifyJwksBasedToken(
token: String,
jwksUri: URL,
): Result<JwtClaims> {
val provider = JwkProviderBuilder(jwksUri)
.cached(10, 60 * 24, TimeUnit.HOURS)
.rateLimited(10, 1, TimeUnit.MINUTES)
.build()
val jwt: DecodedJWT = JWT.decode(token)
val jwk: Jwk = provider[jwt.keyId]
val algorithm: Algorithm = extractAlgorithm(jwk)
return verifyToken(token, algorithm)
}
```
위 코드의 …
> [WEAV-64] 로그인 기능 토큰 발급 지원모듈 개발

- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/AuthRestController.kt
클라이언트측 요청 사항 반영이에요
```
문장훈 — 어제 오후 10:29
@서버 
소셜 로그인 API 호출 시 회원가입 되어있는 경우만 테스트 가능해서
registerToken이 오는 경우는 어떻게 구분할 수 있는지 필요합니다. 
ex. 상태코드 
```
회원가입 필요한 경우 Http 기본 상태코드중 401로 응답하도록 처리했어요.
> [WEAV-70] 소셜 로그인 API, 회원가입 필요 응답 상태코드 401 명세

- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/ApiExceptionType.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/CustomExceptionHandler.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/ErrorResponse.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt
- build.gradle.kts
- buildSrc/src/main/kotlin/Version.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/CustomException.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/CustomExceptionType.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/SystemExceptionType.kt
- support/security/build.gradle.kts
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtExpiredException.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/error/JwtVerificationException.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/exception/JwtExceptionType.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProvider.kt
- support/security/src/test/kotlin/com/studentcenter/weave/support/security/jwt/util/JwtTokenProviderTest.kt
매번 예외 클래스 만들고, 해당 예외 클래스에 대한 처리를 담당할 ExceptionHandler 함수를 추가하는 번거로움을 없애기 위해 CustomException을 구현했어요.
```kotlin
class CustomException(
val type: CustomExceptionType,
override val message: String
) : RuntimeException(message)
```
CustomException간의 구분은 CustomExceptionType을 상속한 enum class를 만들어서 파라미터로 주입받아 CustomException의 속성으로 구분할 수 있어요. (ref. JwtExceptionType)
위와 같이 일관되게 CustomException으로 처리했을때 응답코드가 모두 400이라는 단점이 있지만, 
```kotlin
data class ErrorResponse(
val exceptionCode: String,
val message: String,
val timeStamp: LocalDateTime = LocalDateTime.now(),
)
```
ErrorResponse(예외응답 스키마)의 exceptionCode를 통해 어떤 종류의 예외인지 파악할 수 있고, 클라이언트에게 명세할때에도 enum class를 그대로 전달하면 되기때문에 문서화 측면에서도 편리하다고 생각해요.
위의 변경에 따라 :support:security 모듈의 JwtTokenProvider의 예외처리를 일부 수정하고 이에따라 테스트도 수정했어요.
> [WEAV-72] ✨ 예외처리 핸들러 구현

- application/src/main/kotlin/com/studentcenter/weave/application/port/inbound/UserRegisterUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRepository.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/RegisterUserRequest.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/entity/User.kt
- domain/src/test/kotlin/com/studentcenter/weave/domain/entity/UserTest.kt
- domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/entity/UserFixtureFactory.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UserAuthInfoJpaEntity.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UserJpaEntity.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/repository/UserJpaRepository.kt
- infrastructure/persistence/src/main/resources/application-persistence.yaml
- infrastructure/persistence/src/main/resources/db/migration/V3__create_user.sql
- major, university 엔티티 추가에따른 user 연관관계 필드 id값으로 변경(majorId, universityId)
- UserJpaRepository, UserJpaAdapter, UserJpaEntity 구현
- user 테이블 DDL 정의, 외래키의 경우 직접적으로 FK설정하지 않고 secondary index만 걸어둠
- local에서는 validation에러시 flyway history 자동으로 지우게 만들면 어떨까요?, 
- 로컬에서 개발할때, DB스키마 수정하면서 개발하는데 docker compose down시켰다 다시올리기 번거로운것 같아요.
- 테스트서버, 프로덕션에서만 아래 옵션 사용안하면 큰문제 없을것 같아요,
```
flyway:
clean-disabled: false
clean-on-validation-error: true
```
> [WEAV-121] UserJpaEntity 구현

- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/adapter/UserJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/common/exception/PersistenceException.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/entity/UserJpaEntity.kt
각 모듈별로 `{모듈명}Exceptiontype` enum class 정의해 두고, CustomException에 타입으로 전달해주면 좋을것 같아요
에러 명세는 모든 모듈에 있는 ExceptionType 클래스 스캔해서 API로 전달해주는 방식 생각해봤는데 어떤가요?
> [WEAV-124] 유저 JPA 어댑터 getById 구현

- application/src/main/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImpl.kt
- application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserRegisterApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/service/application/UserSocialLoginApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/service/util/impl/UserTokenServiceImplTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/port/outbound/UserRefreshTokenRepositorySpy.kt
- bootstrap/http/build.gradle.kts
- bootstrap/http/compose-dev.yaml
- bootstrap/http/compose-local.yaml
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/WeaveHttpApplication.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
- infrastructure/redis/build.gradle.kts
- infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/adapter/UserRefreshTokenRedisAdapter.kt
- infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/common/config/RedisConfig.kt
- infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/entity/UserRefreshTokenRedisHash.kt
- infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/repository/UserRefreshTokenRedisRepository.kt
- infrastructure/redis/src/main/resources/application-redis.yaml
- settings.gradle.kts
- Redis 설정
- RefreshToken 발급시 Redis에 저장하는 로직 구현이에요
- 변경 문서가 많지만, 내용은 많지않아요 (의존성 추가때문에 생긴 변경사항이 좀있음)
- 회원가입 요청시 Contorller의 실제 응답이 Swagger 명세랑 다른부분이 있어 수정했어요(상태코드 : ok -> created)
- Redis를 docker compose에 추가함에 따라 개발서버의 메모리 swap이 잦아질 가능성이 높아 추적관찰이 필요해요
- Redis의 노드당 권장 메모리는 4g / 저장된 데이터의 2배 공간을 권장
- 현재 스왑공간을 9g로 늘렸어요, 아래는 redis 붙이기전 개발서버 메모리 사용현황
```
total        used        free      shared  buff/cache   available
Mem:           949Mi       671Mi        72Mi       0.0Ki       205Mi       123Mi
Swap:            9Gi       188Mi       9.8Gi
```
> [WEAV-76] refresh token 발급시 redis 저장 연동

- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UserApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/controller/UserRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/UserGetMyProfileResponse.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/OpenApiConfig.kt
- AccessToken이 필요한 API를 설계할때에는 @SecurityRequirement(name = "AccessToken")를 통해 swagger에 명세할 수 있어요
Swagger 우측 상단에 Authorize가 나타납니다.
access token 집어넣으면 되요
- RefreshToken, RegisterToken의 경우에도 @SecurityRequirement를 적용하고 일관되게 Authorization이라는 헤더키를 사용하게 설계했어야했는데... 이건 추후에 변경하면 좋겠네요
> [WEAV-128] 회원 정보 조회 모의 응답 구성

- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/dto/UserGetMyProfileResponse.kt
height 타입이 어제 말씀드린 value class 이슈때문에 
```
@JvmInline
value class Height(val height: Int) {
init {
require(height in 1..300) {
"키는 1cm 이상 300cm 이하여야 합니다."
}
}
}
```
val value로 안쓰고 val height로 정의 되어 있는데요, 
이부분때문에 springdocs-openapi3 라이브러리에서 객체로 인식되나봅니다.
일단 모의응답만 빠르게 Int타입으로 바꿔놓고 고쳐보겠습니다.
> [WEAV-128] 회원 정보 모의응답 타입 수정

- application/src/main/kotlin/com/studentcenter/weave/application/common/security/context/UserSecurityContext.kt
- application/src/main/kotlin/com/studentcenter/weave/application/common/security/vo/UserAuthentication.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/vo/UserTokenClaimsFixtureFactory.kt
- bootstrap/http/build.gradle.kts
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/config/WebMvcConfig.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/ApiExceptionType.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/annotation/Secured.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/filter/JwtAuthenticationFilter.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/AuthorizationInterceptor.kt
- bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/common/security/filter/JwtAuthenticationFilterTest.kt
- bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/AuthorizationInterceptorTest.kt
- bootstrap/http/src/testFixtures/kotlin/com/studentcenter/weave/bootstrap/controller/AuthorizationInterceptorTestController.kt
- bootstrap/http/src/testFixtures/kotlin/com/studentcenter/weave/bootstrap/controller/JwtAuthenticationFilterTestController.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/annotation/Secured.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/authority/Authentication.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/context/SecurityContext.kt
- support/security/src/main/kotlin/com/studentcenter/weave/support/security/context/SecurityContextHolder.kt
- :support:security 모듈
- SecurityContextHolder 구현 
- 스레드 로컬로 필터에서 인증된 사용자 인증정보를 요청내에서 전역적으로 접근가능하게 만들어둠)
- JwtAuthenticationFilter 
- 토큰이 있으면 파싱해 ContextHolder에 인증 정보 저장, 
- 요청 완료 이후 context clear -> thread 재사용으로 인해 사용자 정보가 다른 요청에 공유되지 않도록 구현
- AuthorizationFilter
- `@Secured` 어노테이션이 붙은 핸들러는 필터를 통해 SecurityContextHolder에 저장된 사용자 정보가 있어야만 접근 가능
- 해당 정보가 없을 경우 HTTP 400 - exceptionCode=API-003 (unauthorized) 응답
- 예외코드들은 400으로 통일하되, exceptionCode로 구분하는것이 좋을것 같아요
- Spring Security 는 러닝커브가 있기도 하고 너무 불필요하게 많은 기능을 제공하는것 같아서 배제시켰어요
> [WEAV-137] 인증 필터, 인가 인터셉터 구현

- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/AuthApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/adapter/api/UserApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/annotation/Secured.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/security/interceptor/AuthorizationInterceptor.kt
- 로그아웃, 사용자 프로필 API에 Secured 어노테이션을 적용했어요
- 인터셉터에 핸들러 메서드 여부를 체크하는 로직이 없어 Swagger동작에 오류가 있었어요, 핸들러 메서드 여부 확인하도록 변경했어요 (정적 리소스 요청시에는 핸들러 메서드가 아니기에 분기 필요)
- 적용 방법에 대해 [문서화](https://www.notion.so/student-center/API-7e5c043eeac64ddb9b10439d49aff693)했어요
> [WEAV-137] Secured 어노테이션 적용 (로그아웃, 사용자 프로필 API)

- application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSocialLoginApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/KakaoOpenIdTokenResolveStrategyTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/OpenIdPropertiesFixtureFactory.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
- domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
애플 소셜 로그인 API 구현 완료했습니다. 
문서 숙지가 오래 걸렸고 코드는 전반적으로 산님이 구조 잡아두셔서 거즘 변경사항 없이 할 수 있었네요 😊😊
* Nickname의 경우에는 idTokenResolve해서 반환할 때, 빈 문자열 `""` 태워서 반환하는 방식으로 우선 적용했습니다!
https://www.notion.so/student-center/API-6423f88b21b941da86acf5e79b99c93f
> [WEAV-132] 애플 소셜 로그인 API 구현

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamGetMyUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/vo/MeetingTeamInfo.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollRequest.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt
- 내 미팅팀 조회 응답 모의 응답 구현했어요
- ApplicationService에 있는 내용들은 모의 객체들이에요
- no-offset방식의 무한스크롤 공통 요청, 응답을 위해 ScrollRequest, ScrollResponse를 구현했어요
- Response 의 경우 abstract로 두고 상속해서 구현하도록 만들어 두었어요.
https://www.notion.so/student-center/API-776fbb2418f540ca81e7c0a06425ece4
> [WEAV-187] 내 미팅팀 조회 응답 API 모의 응답 구현

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingMemberRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserQueryUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserQueryApplicationService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamCreateApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImplTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingMemberRepositorySpy.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/inbound/UserQueryUseCaseStub.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingMember.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeam.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/enums/MeetingMemberRole.kt
- domain/src/test/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamTest.kt
- domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/meeting/entity/MeetingTeamFixtureFactory.kt
- domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingMemberJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingMemberJpaEntity.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/entity/MeetingTeamJpaEntity.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingMemberJpaRepository.kt
- infrastructure/persistence/src/main/resources/application-persistence.yaml
- infrastructure/persistence/src/main/resources/db/migration/V13__create_meeting_member.sql
- 내 미팅팀 조회 유스케이스 개발과정에서 일반 유저, 팀장을 구분하는 로직이 복잡해지는 부분이있어 leader를 meeting_member로 정규화했어요.
- 리팩터링 됨에 따라 미팅팀 멤버 추가 메서드를 구현했어요
- 미팅팀에 성별을 추가했어요
- UserQueryUseCase를 추가했어요(타 도메인 조회용)
- 메서드, 변수, 클래스 이름 더 적절한게 생각나면 적극적으로 추천해주세요 
- PR이 좀 커요 지송 🙇
> [WEAV-176] 미팅팀 생성 유스케이스 리팩터링

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamGetMyUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingMemberRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamGetMyApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/vo/MeetingTeamInfo.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingMemberRepositorySpy.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyRequest.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamGetMyResponse.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/user/dto/UserRegisterRequest.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingMemberJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingMemberJpaRepository.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingTeamJpaRepository.kt
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/dto/ScrollResponse.kt
- 내 미팅팀 조회 유스케이스 구현했어요
- 조회 usecase에 대해서도 단위 테스트가 필요할까요?, 조회의 경우 단위테스트보다는 통합테스트가 효용성이 있는것 같아서요
- 현재 암묵적으로 사용하는 클래스 네이밍 컨벤션 중에 도메인 먼저 사용하는 케이스가 있는데,(ex MeetingTeamGetMyUseCase.kt) 여기에 대해서는 자연스러운 문장(GetMyMeetingTeamListUseCase.kt)으로 표현하는게 좋을것 같은데 어떠신가요? (추후 리팩터링 제안)
> [WEAV-176] 내 미팅팀 조회 유스케이스 구현

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/MeetingTeamDeleteUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingMemberRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingTeamRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamDeleteApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingTeamDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingTeamDomainServiceImpl.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingTeamDeleteApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingMemberRepositorySpy.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingTeamRepositorySpy.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingMemberJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingTeamJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingMemberJpaRepository.kt
- request
- method & path: `[DELETE] /api/meeting-teams/{id}`
- id : 미팅 팀의 ID
- response
- 정상 처리된 경우
- status code: `204 No Content`
> [WEAV-202] 미팅팀 삭제 유스케이스 구현

- domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/enums/Location.kt
가독성을 위해 중간 구분점 큰 것으로 변경하였습니다.
> 건대·성수 -> 건대•성수
> [WEAV-228] 위치 정보 조회 가독성 수정

- domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummary.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/entity/MeetingTeamMemberSummaryJpaEntity.kt
- infrastructure/persistence/src/main/resources/db/migration/V14__create_meeting_team_member_summary.sql
**MeetingTeamMemberSummary**
- 미팅 팀 확정시 생성되는 팀내 멤버 정보 대한 요약 도메인
- 목록조회시 필터 (가장 어린 년생, 가장 나이많은 년생)
- 상세 조회시 케미(팀 MBTI)
- 미팅팀 멤버 요약 도메인 정의
```mermaid
erDiagram
MeetingTeamEntity ||--|| MeetingTeamMemberSummaryEntity : has
MeetingTeamEntity {
UUID id
}
MeetingTeamMemberSummaryEntity {
UUID id
UUID meeting_team_id
string team_mbti
int youngest_member_birth_year
int oldest_member_birth_year
LocalDateTime created_at
}
```
> [WEAV-231] 미팅팀 멤버 요약 도메인 정의

- domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Mbti.kt
- domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/MbtiTest.kt
- 주어진 MBTI 유형들의 목록에서 가장 우세한 성격 유형을 결정하는 로직을 구현했어요
- MBTI_UPPERCASE_SCORE와 MBTI_LOWERCASE_SCORE: 대문자 MBTI 지표는 2점, 소문자는 1점의 가중치를 두어, 대문자로 표시된 성격 특성을 더 강하게 표현해요
1. 초기에 mbtiScores 맵은 각 MBTI 성격 지표(E, I, N, S, F, T, P, J)를 키로 하고, 각각의 초기 점수를 0으로 설정해요
2. 주어진 mbtis 목록을 순회하며, 각 MBTI 유형의 문자를 대문자로 변환하고, 해당 문자가 대문자인지 여부에 따라 점수(대문자는 2점, 소문자는 1점)를 부여하고, 각 문자의 점수는 mbtiScores 맵에 누적해요
3. 모든 MBTI 유형에 대해 점수를 계산한 후, buildString을 사용하여 새로운 MBTI 유형 문자열을 생성해요. 네 개의 성격 차원 각각에 대해 selectDominantTrait 함수를 호출하여 우세한 특성(E/I, S/N, F/T, J/P)을 선택하는 방식으로 진행돼요
4. selectDominantTrait 함수는 두 성격 지표(예: E와 I)의 점수를 비교하고, 더 높은 점수를 가진 특성을 반환해요. 점수가 같은 경우 첫 번째 특성(이 예에서는 E)을 반환해요
> [WEAV-236] 대표 MBTI 계산 로직 작성

- application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingTeamExceptionType.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamLeaveUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingMemberRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingMemberRepositorySpy.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingMemberJpaAdapter.kt
- 내팀화면, 멤버의 미팅팀 나가기 기능 개발
- 멤버의 미팅팀 나가기
- 만약 팀이 공개된 상태(status = PUBLISH)일 경우 나갈 수 없다.
- 만약 유저가 해당 팀에 속해 있지 않을 경우 나갈 수 없다.
- 만약 유저가 해당 팀의 멤버가 아닌경우(리더인 경우) 나갈 수 없다.
**POST /api/meeting-teams/{id}/leave**
- **Auth Required:** Yes (토큰 기반 인증을 사용, 요청 헤더에 **`Authorization: Bearer <token>`** 포함)
- **Request**
- method & path: `[DELETE] /api/meeting-teams/{id}/members/me`
- **Response**
- 정상 처리된 경우
- status code: `200 OK`
> [WEAV-227] 미팅팀 나가기 API 구현

- application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/UserTokenServiceImpl.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/vo/UserAuthentication.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/vo/UserTokenClaims.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserGetMyProfileApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserLogoutApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserModifyMyMbtiApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSendVerificationNumberEmailApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyAnimalTypeApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSetMyHeightApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserUnregisterApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserVerifyVerificationNumberApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/UserTokenServiceImplTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/vo/UserAuthenticationFixtureFactory.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/vo/UserTokenClaimsFixtureFactory.kt
- 미팅팀 목록조회시 회원의 gender를 확인하고 반대되는 성별의 미팅팀을 조회해야하는데, 이때 현재 유저의 성별 정보가 필요해요.
- 매번 DB에서 조회하기 보다 token claim으로 성별을 가지고 있으면, DB부하를 줄이면서 처리하기 용이하다 생각해서 access token에 gender를 추가했어요
- Access Token Claim에 Gender를 추가했어요
- claim추가에 따른 테스트 수정사항이 있었어요.
- 이후에도 token claim수정에 따른 테스트 수정이 많이 전파되지 않도록 UserAuthenticationFxitureFactory를 구현해 적용했어요
> [WEAV-237] User Access Token Claims gender 추가

- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamMemberSummaryRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/MeetingTeamDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamDeleteApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamEditApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImplTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamMemberSummaryRepositorySpy.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeam.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummary.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamMemberSummaryJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamMemberSummaryJpaRepository.kt
- 미팅팀의 멤버가 모두 초대 되면, 팀을 공개하기위해 호출할 수 있는 publish 메서드를 작성했어요.
- 미팅팀에 참여한 멤버가 설정된 팀 인원수보다 적은 경우 -> 예외
- 미팅팀이 이미 공개된 상태인 경우 -> 미팅팀 반환(멱등)
- 미팅팀에 참여한 멤버가 설정된 팀 인원수와 같고, 공개된 상태가 아닌경우 -> 멤버 요약정보 생성 및 공개 상태로 변경
- 현재 메서드의 경우 미팅팀에 초대된 멤버가 모두 가입하면 호출해야 하는 메서드인데요, 이경우 메서드 사용자 측에서 어떤 메서드들을 호출해야하는지 알고 직접적으로 호출해야 하는 강하게 결합된 상태로 보여요. (미팅 팀원 초대 구현에서 반영해야함)
- 이렇게 하지 말고, 모든 멤버가 초대되었다 라는 이벤트를 발행하면, 해당 event를 consume하는 측에서 어떤 메서드들을 호출해야하는지만 알면  좀더 유연하게 처리 가능할것 같은데, 어떻게 생각하시나요?
- Spring 자체 message queue를 활용하면 공수가 크게 들어가지는 않을것 같아요
- 이러한 구현을 위해서는 inbound를 다음과 같이 분리해야 할것같아요.
- 사용자의 도메인 조작 요청(UseCase), 타 도메인의 조작요청(EventHandler), 쿼리(QueryHandler)
> [WEAV-234] 미팅팀 공개 로직 구현

- application/src/main/resources/application-application.yaml
* 생성되는 초대 링크 URL을 다음과 같이 수정했습니다.
[변경 전]
`https://api.dev.team-weave.me?code=`
[변경 후]
`https://api.dev.team-weave.me/invitations?code=`
* 2/23 9시쯤 해당 초대 링크 동작 + 앱링크 관련해서 AOS 장훈님과 함께 테스팅 진행하기로 했습니다!
> [WEAV-252] 초대 링크 생성 API URL 수정

- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetDetailApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamRepositorySpy.kt
- MeetingRepository 팀과 멤버 유저를 조인해서 쿼리하는 메서드(getByMemberUserId)가 있는데, 해당 메서드의 Spy 응답을 단순하게 first로 만들어 두어서 테스트가 실패했어요.
- 구체적으로 상황 지정할 수 있도록 spy 메서드 추가하고 테스트 수정했어요
> [WEAV-246] 팀 상세조회 응답 테스트 수정

- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/adapter/MeetingTeamJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meetingTeam/repository/MeetingTeamJpaRepository.kt
- 미팅팀 목록조회시 Location이 여러개일경우 쿼리가 제대로 되지 않는 현상을 해결했어요
- JPQL에서는 List를 사용하지 말고 Array를 사용해야함
> [WEAV-153] 미팅팀 목록 조회 다수 Location 쿼리 버그 수정

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/CancelAllMeetingUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/CancelAllMeetingApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamLeaveApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt
- 팀이 공개된 상태에서 멤버가 나갈 경우 모든 완료되지 않은 미팅은 취소 처리되며 팀은 삭제처리합니다
> [WEAV-000] Fix delete member apply published team cancel logic

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/ScrollPreparedMeetingUseCase.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/ScrollPreparedMeetingApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingDomainService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/impl/MeetingDomainServiceImpl.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/vo/PreparedMeetingInfo.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/ScrollPendingMeetingApplicationServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/ScrollPreparedMeetingApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingRepositorySpy.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingTeamInfoCreator.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamDto.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PendingMeetingScrollResponse.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollRequest.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/PreparedMeetingScrollResponse.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/adapter/MeetingJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/meeting/repository/MeetingJpaRepository.kt
- 매칭된 팀 스크롤 조회 구현 및 테스트
- 팀 인포 생성 오브젝트 분리
- 이후 미팅 상태 확장 시 코드 수정을 위한 주석
> [WEAV-276] 매칭된 팀 스크롤 조회

- .github/workflows/develop_server_integrator.yaml
이 Pull Request는 기존의 HeadVer 버전 시스템을 개선하고 GitHub 릴리스 생성을 자동화하는 내용을 포함합니다. 주요 변경 사항은 다음과 같습니다:
- Git 태그 생성 및 푸시를 "Create Release" 액션으로 대체하여 GitHub 릴리스 생성을 자동화합니다.
- 릴리스 노트에 HeadVer 버전 정보와 함께 해당 릴리스에 포함된 커밋의 변경 사항을 포함시킵니다.
- `generate_changelog` 단계를 추가하여 이전 릴리스부터 현재 릴리스까지의 커밋 메시지를 기반으로 변경 로그를 생성합니다.
- "Create Release" 액션을 사용하여 GitHub 릴리스를 자동으로 생성합니다.
- `GITHUB_TOKEN` 시크릿을 환경 변수로 설정하여 액션에서 사용할 수 있도록 합니다.
- `tag_name`은 생성된 HeadVer 버전을 사용합니다.
- `release_name`은 "Release" 접두사와 HeadVer 버전을 사용합니다.
- `body`에는 HeadVer 버전의 세부 정보와 변경 로그를 포함합니다.
- `generate_changelog` 단계에서는 `git log` 명령어를 사용하여 이전 릴리스부터 현재 릴리스까지의 커밋 메시지를 가져와 변경 로그를 생성합니다.
- 이전 릴리스 태그는 `git describe` 명령어를 사용하여 가져옵니다.
- 현재 릴리스 태그는 `steps.generate_version.outputs.version`을 사용합니다.
- 생성된 변경 로그는 `steps.generate_changelog.outputs.changelog`로 …
> [WEAV-293]  🚀 HeadVer 버전 시스템 태그 생성 수정 및 GitHub 릴리스 자동화

- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/common/exception/UnknownExceptionHandler.kt
- bootstrap/http/src/main/resources/application.yaml
- infrastructure/persistence/src/main/resources/application-persistence.yaml
- support/common/src/main/kotlin/com/studentcenter/weave/support/common/exception/SystemExceptionType.kt
- 악의적인 정적 리소스 요청으로 인해 로그 파악이 힘든점을 개선하기위해 정적 리소스 요청 리소스 매핑을 불가능하도록 하고, NoHandlerException에 대한 핸들링을 추가했습니다.
- integration 테스트시 sql 로깅을 제거해 테스트시 로그파악이 쉽도록 개선했습니다.
> [WEAV-000] 정적 리소스 요청 stacktrace 로그 제거

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/GetUser.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/GetUserService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/inbound/GetUserStub.kt
- domain/src/testFixtures/kotlin/com/studentcenter/weave/domain/user/entity/UserFixtureFactory.kt
- 이메일 인증처리가 완료된경우 User의 isUnivVerified가 true가 되므로, userUniversityVerificationInfo의 존재여부를 조회하는것이 아닌 User를 쿼리해 내용을 확인하는방식으로 변경
- isUserUniversityVerified 메서드 제거, User객체로 직접 확인하는 방식으로 변경
> [WEAV-000] isUserUniversityVerified 메서드 제거, User객체로 직접 확인하는 방식으로 변경

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingRequestApplicationServiceTest.kt
현재 validation순서가
1. 대학교 인증을 했는가?
2. 내팀이 있는가?
순서로 진행이 되는데, 대학교 인증이 되지 않은경우에도 팀을 만들수 있긴 하기때문에,
1. 내팀이 있는가?
2. 대학교 인증을 했는가?
순서로 진행되어야한다는 클라이언트 의견을 반영
> [WEAV-000] 미팅 요청 validation 순서 조정

- application/src/main/kotlin/com/studentcenter/weave/application/chat/port/inbound/GetChatMessage.kt
- application/src/main/kotlin/com/studentcenter/weave/application/chat/port/outbound/ChatMessageRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/chat/service/GetChatMessageService.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/chat/api/ChatMessageApi.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/chat/controller/ChatMessageRestController.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/chat/dto/GetChatMessagesRequest.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/chat/dto/GetChatMessagesResponse.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/adapter/ChatMessageJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/chat/repository/ChatMessageJpaRepository.kt
- [설계 문서](https://www.notion.so/weave-org/9e998df857af46ceaf27af4755427bc7?p=82120283420c49bb9c5295780ecfda14&pm=s)
> [WEAV-329] 이전 채팅메시지 조회 API 구현

- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/CreateMeetingAttendance.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingEventPublisher.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/CreateMeetingAttendanceService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/domain/MeetingEventService.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingEventHandler.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingRestController.kt
- bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/integration/CreateMeetingAttendanceIntegrationTest.kt
- bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingEventHandlerTest.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/common/AggregateRoot.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/common/DomainEntity.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/common/DomainEvent.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/entity/Meeting.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meeting/event/MeetingCompletedEvent.kt
- 미팅 매칭시 이벤트를 발행하고, 해당 이벤트를 전달 받으면 채팅방을 생성하도록 구현했어요
- 도메인 이벤트를 구현하면서 DomainEntity 추상 클래스를 도입했는데, approve되면 다른도메인 엔티티에도 일괄적으로 적용하는 리팩토링 진행할게요
```mermaid
graph TD
A[CreateMeetingAttendanceService] -->|"invoke(meetingId, attendance)"| B{미팅 참여 여부 확인}
B -->|마지막 참여자| C["Meeting.complete()"]
C --> D["MeetingDomainService.save(meeting)"]
C --> E["MeetingCompletedEvent 생성"]
E --> F["MeetingEventPublisher.publish(event)"]
F --> G["ApplicationEventPublisher.publishEvent(event)"]
G --> H["MeetingEventHandler.handleMeetingEvent(event)"]
H --> I["CreateChatRoom.invoke(meeting)"]
B -->|마지막 참여자 아님| J[종료]
```
> [WEAV-331] 미팅 매칭시 채팅방 생성

- application/src/main/kotlin/com/studentcenter/weave/application/chat/port/inbound/CreateChatRoom.kt
- application/src/main/kotlin/com/studentcenter/weave/application/chat/service/CreateChatRoomService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/inbound/NotifyMeetingEvent.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingEventMessagePort.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/CreateMeetingAttendanceService.kt
- application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/NotifyMeetingEventService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/chat/service/CreateChatRoomServiceTest.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meeting/service/application/NotifyMeetingEventServiceTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/meeting/outbound/MeetingEventMessagePortSpy.kt
- bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingEventHandler.kt
- bootstrap/http/src/test/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingEventHandlerTest.kt
- infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/meeting/adaptor/MeetingEventMessageDiscordAdaptor.kt
- 미팅 매칭 완료시 디스코드 메시지 발송 로직을 기존의 유스케이스(어플리케이션 서비스)에서 수행하던 것에서 이벤트 리스너로 옮기는 리팩토링을 진행했어요
- MeetingEventHandler에서 MeetingCompletedEvent 이벤트를 받아 비동기로 NotifyMeetingEvent.notifyMeetingCompleted() 메서드를 호출하도록 하였습니다.
- NotifyMeetingEventService에서는 전달받은 MeetingCompletedEvent를 가지고 필요한 데이터를 조합한 후 MeetingEventMessagePort를 통해 메시지 발송을 위임합니다.
- 기존의 MeetingEventPort와 MeetingEventDiscordAdaptor는 각각 MeetingEventMessagePort와 MeetingEventMessageDiscordAdaptor로 이름을 변경하였습니다.
- 어제 구두로 논의했던 내용중에서 도메인 이벤트를 받는 리스너들은 bootstrap의 event패키지에 모아두자 라고 이야기 했던 부분이 고민이 되네요, `특정 도메인의 Primary Adatper의 역할을 한다` 라고 본다면 각 도메인들의 패키지에 위치하는게 어색한데,(다른 도메인의 inbound port를 호출할 수도 있으니), `어떤 도메인의 이벤트를 처리하느냐` 의 관점에서본다면 도메인 패키지에 위치하는것도 큰문제는 없어보이고 되려 외부에서 보기엔 더 직관적인 위치가 될것같아서요
> [WEAV-000] 미팅매칭시 이벤트 메시지 발송 리펙터링

- application/src/main/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepository.kt
- application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/VerifyUniversityVerificationNumberService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/VerifyUniversityVerificationNumberTest.kt
- application/src/testFixtures/kotlin/com/studentcenter/weave/application/user/port/outbound/UserRepositorySpy.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/adapter/UserJpaAdapter.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/entity/PreRegisteredEmail.kt
- infrastructure/persistence/src/main/kotlin/com/studentcenter/weave/infrastructure/persistence/user/repository/PreRegisteredEmailRepository.kt
- infrastructure/persistence/src/main/resources/db/migration/V21__create_pre_registered_user.sql
- 사전 예약자의 경우 실 2배 지급가능하도록 구현해뒀어요. 배포후 테이블 생성되면 예약자 이메일은 수동으로 기입할 예정입니다.
- `VerifyUniversityVerificationNumberTest.kt` 테스트 리팩터링이 필요할것 같아요, 다른 application service에 의존적인 부분이 있네요 (우선 최대한 기존 테스트 형태 유지 하면서 기능 구현해뒀어요)
> [WEAV-333] 사전 예약자 실 2배 지급 기능 구현

- application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/JoinMeetingTeamService.kt
- application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/JoinMeetingTeamServiceTest.kt
- domain/src/main/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummary.kt
- domain/src/test/kotlin/com/studentcenter/weave/domain/meetingTeam/entity/MeetingTeamMemberSummaryTest.kt
- 미팅 팀 공개상태로 변경시 팀원 요약정보가 생성되지 않는 문제 발생
- 미팅팀 공개상태 전환 여부 확인 및 요약정보 생성 및 저장 Service로직 구현
> [WEAV-000] 미팅 팀원 요약정보 생성 핫픽스
